#!/usr/bin/env python3
"""Inject benchmark statistics into LaTeX fragments and sync figures from min-mem."""

from __future__ import annotations

import json
import shutil
from pathlib import Path

MIN_MEM_ROOT = Path(__file__).resolve().parents[1].parent / "min-mem"
RESULTS = MIN_MEM_ROOT / "experiments" / "results.json"
FIG_SRC = MIN_MEM_ROOT / "experiments" / "figures"
PAPER_ROOT = Path(__file__).resolve().parents[1]
FIG_DST = PAPER_ROOT / "figures"
GENERATED = PAPER_ROOT / "generated"


def fmt(x: float, digits: int = 1) -> str:
    return f"{x:.{digits}f}"


def main() -> None:
    data = json.loads(RESULTS.read_text(encoding="utf-8"))
    s = data["summary"]
    gzip = data["gzip_baseline"]["mean_savings_pct"]
    cats = data["by_category_char_savings"]

    GENERATED.mkdir(exist_ok=True)
    FIG_DST.mkdir(exist_ok=True)

    for ext in ("pdf", "png"):
        for fig in FIG_SRC.glob(f"fig_*.{ext}"):
            shutil.copy2(fig, FIG_DST / fig.name)

    stats_tex = f"""% Auto-generated by scripts/generate_paper.py — do not edit
\\newcommand{{\\CorpusSize}}{{{data['corpus_size']}}}
\\newcommand{{\\DictSize}}{{{data['dictionary_size']}}}
\\newcommand{{\\MinMemCharSavings}}{{{fmt(s['min-mem (full)']['char_savings_pct_mean'])}}}
\\newcommand{{\\MinMemTokenSavings}}{{{fmt(s['min-mem (full)']['token_savings_pct_mean'], 2)}}}
\\newcommand{{\\MinMemNounPres}}{{{fmt(s['min-mem (full)']['nouns_preserved_pct_mean'])}}}
\\newcommand{{\\MinMemSynonym}}{{{fmt(s['min-mem (full)']['synonym_aware_pct_mean'])}}}
\\newcommand{{\\MinMemSwaps}}{{{fmt(s['min-mem (full)']['replacements_mean'], 1)}}}
\\newcommand{{\\NaiveCharSavings}}{{{fmt(s['naive-dict']['char_savings_pct_mean'])}}}
\\newcommand{{\\NaiveNounPres}}{{{fmt(s['naive-dict']['nouns_preserved_pct_mean'])}}}
\\newcommand{{\\PhraseCharSavings}}{{{fmt(s['phrase-only']['char_savings_pct_mean'], 2)}}}
\\newcommand{{\\NoInflCharSavings}}{{{fmt(s['no-inflection']['char_savings_pct_mean'])}}}
\\newcommand{{\\GzipSavings}}{{{fmt(gzip)}}}
\\newcommand{{\\CatVerbosity}}{{{fmt(cats.get('high_verbosity', 0))}}}
\\newcommand{{\\CatPrefs}}{{{fmt(cats.get('user_preferences', 0))}}}
\\newcommand{{\\CatEntity}}{{{fmt(cats.get('entity_heavy', 0))}}}
"""
    (GENERATED / "stats.tex").write_text(stats_tex, encoding="utf-8")
    print(f"Generated {GENERATED / 'stats.tex'}")
    print(f"Synced figures to {FIG_DST}")


if __name__ == "__main__":
    main()
